import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "X-Solution",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>): React.JSX.Element
{
  return (
    <html lang="ru">
    <body>
    {children}
    </body>
    </html>
  );
}
